apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "codebase.fullname" . }}
spec:
  replicas: {{.Values.scale}}
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: {{ .Values.image.repository | quote }}
        ports:
        - containerPort: 80
